version: '3.7'

version: "3.7"
services:
  dynamicelem:
    container_name: "dynamicelem"
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DB_SCHEMA= postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/dynamic-element